### ISSUE TITLE
Money is show as 0 when a dungeon/shop is opened

### ISSUE THREAD

**Issue by tklaxbro** [Ishadijcks/pokeclicker#247]
As the title says, when something is opened the coins are shown as 0 and once you leave back to the main tab and kill someone the money is updated to normal

**Comment by Aegyo** [comment]
moveToTown switches the gamestate to idle, so knockout disables a few things, like the resource display. Then we have the gamestate switch to town, so the display appears again, and the money gets filled with the default value of 0.

This could be fixed with a Game.updateMoney() at the end of moveToTown, but it would do the animation from 0 to however much you have even though you don't gain any money. There is also the option of just setting the innerText of the element with jquery, but that doesn't feel quite right.

I think a better option would be to separate out the resource view from the rest of the interaction view stuff, and have the resources always visible. This could be part of #74, I think Isha mentioned something like that before when talking about that issue.

**Comment by tklaxbro** [comment]
What would be the issue with just making a function to change the value without an animation?

**Comment by tklaxbro** [comment]
Just adding a simply function into Main.ts: `static basicMoneyUpdate() {
        $("#playerMoney").text(player.money)
    }`

and adding a `Game.basicMoneyUpdate()` after the gamestate change to town

**Comment by Aegyo** [comment]
It would work, but there are potentially lots of other places where the game state becomes idle, like when opening the safari zone.

I'm just not a fan of having a bunch of basicMoneyUpdate hotfixes in parts of code which shouldn't really need to do anything money related, but idk how Isha feels about having the resource bar always visible.

**Comment by tklaxbro** [comment]
After further testing I realized that the text for playerMoney in the html was set at: 
```html
<span id="playerMoney">0</span>
```
but when I changed it to: 
```html
<span id="playerMoney" data-bind="text: player.money"></span>
```
the animations worked fine and it stayed the current number in towns/shops

**Comment by BaineGames** [comment]
pr #255 addresses this issue. not the prettiest - but it's somethin lol
